### ISSUE TITLE
Download of expired file as user error

### ISSUE THREAD

**Issue by ujovlado** [keboola/docker-bundle#384] opened 2019-01-14 13:01 UTC
If i try to download file which doesn't exist (e.g. is expired) it should not fail with internal err.

`docker-eaed1aee366254066b1ac5e7bd0b7a7d`

```
{"class":"Keboola\\InputMapping\\Exception\\InputOperationException","message":"Failed to download file in.c-keboola-ex-currency-380638787.rates.csv 400139666"...
```

Client err from aws:

```
Client error: `GET https://kbc-.....
...3` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message> (truncated...)
...

**Comment by odinuv** [comment] 2019-01-14 13:03
duplicate of https://github.com/keboola/connection/issues/1080

**Comment by Halama** [comment] 2019-04-24 08:53
Minulý týden se objevilo několikrát a Fisa to hlásí https://keboola.zendesk.com/agent/tickets/10372

**Comment by odinuv** [comment] 2020-08-12 09:28
fixed in https://keboola.atlassian.net/browse/KBC-161

**Closed by odinuv** 2020-08-12 09:28 UTC
