### ISSUE TITLE
Download of file resulting in 403

### ISSUE THREAD

**Issue by pivnicek** [keboola/docker-bundle#431] opened 2019-06-17 10:11 UTC
Somehow, I'm not sure how, an attempt to download a file from s3 resulted in a 403 response from AWS.  

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/06/17/11/2019-06-17-11-50-30-5d07626604d86-exception

https://keboola.slack.com/archives/C09U3R1J4/p1560765064003800

**Comment by ujovlado** [comment] 2019-06-17 10:27
I think it's that classic problem when downloading expired file.

Check the path:

```
...files/2018/12/14/...
```

**Comment by pivnicek** [comment] 2019-06-17 10:32
Ah, yes, it's > 6 months.  But I checked your issue https://github.com/keboola/docker-bundle/issues/384 but it returned 404 in that case so wasn't sure.  Thanks Ujo.

**Comment by ujovlado** [comment] 2019-06-17 10:35
There's already PR for that in connection, we'll fix it soon. Hopefully.

**Comment by odinuv** [comment] 2019-06-18 14:11
duplicate of https://github.com/keboola/docker-bundle/issues/384
duplicate of https://github.com/keboola/input-mapping/issues/18
duplicate of https://github.com/keboola/connection/issues/1080

:)

**Closed by odinuv** 2019-06-18 14:11 UTC

**Comment by pivnicek** [comment] 2019-06-18 14:12
hahaha, sorry!
